//
// Created by henry on 6/24/21.
//

#ifndef HLTE_TERMINAL_FORMATTING_H
#define HLTE_TERMINAL_FORMATTING_H

#define BACKGROUND_BLACK 40
#define BACKGROUND_RED 41
#define BACKGROUND_GREEN 42
#define BACKGROUND_YELLOW 43
#define BACKGROUND_BLUE 44
#define BACKGROUND_MAGENTA 45
#define BACKGROUND_CYAN 46
#define BACKGROUND_WHITE 47

#define BACKGROUND_BRIGHT_BLACK 100
#define BACKGROUND_BRIGHT_RED 101
#define BACKGROUND_BRIGHT_GREEN 102
#define BACKGROUND_BRIGHT_YELLOW 103
#define BACKGROUND_BRIGHT_BLUE 104
#define BACKGROUND_BRIGHT_MAGENTA 105
#define BACKGROUND_BRIGHT_CYAN 106
#define BACKGROUND_BRIGHT_WHITE 107

#define TEXT_BLACK 30
#define TEXT_RED 31
#define TEXT_GREEN 32
#define TEXT_YELLOW 33
#define TEXT_BLUE 34
#define TEXT_MAGENTA 35
#define TEXT_CYAN 36
#define TEXT_WHITE 37
#define TEXT_WHITE 37
#define TEXT_GREY 90
 
#define TEXT_BRIGHT_BLACK 90
#define TEXT_BRIGHT_RED 91
#define TEXT_BRIGHT_GREEN 92
#define TEXT_BRIGHT_YELLOW 93
#define TEXT_BRIGHT_BLUE 94
#define TEXT_BRIGHT_MAGENTA 95
#define TEXT_BRIGHT_CYAN 96
#define TEXT_BRIGHT_WHITE 97

#endif //HLTE_TERMINAL_FORMATTING_H
